version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install poetry
          command: |
            sudo -H python3 -m pip install --upgrade pip
            sudo -H python3 -m pip install --upgrade poetry

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Install dependencies
          command: |
            poetry config --local virtualenvs.in-project true
            poetry install

      - save_cache:
          paths:
            - ./.venv
            - ~/.cache/pypoetry
          key: v2-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Tests
          command: |
            make test
