version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo -H pip3 install --upgrade pip
            pip3 install --user pipenv
            pipenv sync --dev
            pipenv clean

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Tests
          command: |
            make test
