version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install poetry
          command: |
            sudo -H python3 -m pip install --upgrade pip
            sudo -H python3 -m pip install --upgrade poetry

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Install dependencies
          command: |
            poetry config --local virtualenvs.in-project true
            poetry install

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Tests
          command: |
            make test
